#include <OpenXLSX.hpp>
#include <catch2/catch_all.hpp>
#include <filesystem>
#include <vector>
#include <string>
#include <iostream>

using namespace OpenXLSX;

TEST_CASE("Cross-Engine Compatibility", "[Compatibility]")
{
    // These files are generated by scripts and have known structures
    std::vector<std::string> generatorFiles = {
        "openpyxl_generated.xlsx",
        "excelize_generated.xlsx"
    };

    // These files are static exports from various SaaS/Desktop platforms
    std::vector<std::string> realWorldFiles = {
        "google_spreadsheets.xlsx",
        "tencent_sheet.xlsx"
    };

    auto resolvePath = [](const std::string& file) -> std::string {
        std::string filepath = "Fixtures/" + file;
        if (!std::filesystem::exists(filepath)) {
            if (std::filesystem::exists(file)) {
                filepath = file;
            } else {
                filepath = "../Tests/Fixtures/" + file;
            }
        }
        return filepath;
    };

    for (const auto& file : generatorFiles) {
        SECTION("Load, verify and re-save generator file: " + file) {
            std::string filepath = resolvePath(file);
            if (!std::filesystem::exists(filepath)) FAIL("Test fixture not found: " << file);

            INFO("Testing compatibility with: " << filepath);
            
            XLDocument doc;
            REQUIRE_NOTHROW(doc.open(filepath));

            auto wks = doc.workbook().worksheet("TestSheet");
            
            // 1. Verify Basic Values
            REQUIRE(wks.cell("A1").value().get<std::string>().find("Hello from") != std::string::npos);
            REQUIRE(wks.cell("A2").value().get<int64_t>() == 42);
            REQUIRE(wks.cell("A3").value().get<double>() == Catch::Approx(3.1415));
            
            // Note: Date/Time might be read as a float (Excel serial date) depending on OpenXLSX parsing, 
            // but we at least ensure it doesn't crash and has a value.
            REQUIRE(wks.cell("A4").value().type() != XLValueType::Empty);
            
            // Formulas
            REQUIRE(wks.cell("A5").hasFormula() == true);
            REQUIRE(wks.cell("A5").formula().get().find("SUM") != std::string::npos);

            // Styling presence check
            REQUIRE(wks.cell("B1").value().get<std::string>() == "Styled");

            // Merged Cells check
            REQUIRE(wks.cell("C1").value().get<std::string>() == "Merged Area");

            // Second Sheet
            auto wks2_orig = doc.workbook().worksheet("SecondSheet");
            REQUIRE(wks2_orig.cell("A1").value().get<std::string>() == "Data in second sheet");

            // 2. Modify content
            wks.cell("C1").value() = "Modified by OpenXLSX";

            // 3. Save as new file (this ensures we don't break the original but tests the write-path)
            std::string outFile = "modified_" + file;
            REQUIRE_NOTHROW(doc.saveAs(outFile, XLForceOverwrite));
            doc.close();

            // 4. Re-open to verify our write didn't corrupt it
            XLDocument doc2;
            REQUIRE_NOTHROW(doc2.open(outFile));
            auto wks2 = doc2.workbook().worksheet("TestSheet");
            REQUIRE(wks2.cell("C1").value().get<std::string>() == "Modified by OpenXLSX");
            doc2.close();
            
            std::filesystem::remove(outFile);
        }
    }

    for (const auto& file : realWorldFiles) {
        SECTION("Load, verify and re-save real-world file: " + file) {
            std::string filepath = resolvePath(file);
            if (!std::filesystem::exists(filepath)) {
                WARN("Real-world fixture missing, skipping test: " << file);
                return; // Skip if user hasn't downloaded them
            }

            INFO("Testing compatibility with: " << filepath);
            
            XLDocument doc;
            // Ensure OpenXLSX can successfully parse the file
            REQUIRE_NOTHROW(doc.open(filepath));

            // Ensure we can retrieve at least one worksheet
            auto sheetNames = doc.workbook().worksheetNames();
            REQUIRE_FALSE(sheetNames.empty());
            
            auto wks = doc.workbook().worksheet(sheetNames[0]);
            
            // Perform a safe modification
            wks.cell("ZZ99").value() = "OpenXLSX Compatibility Mark";

            std::string outFile = "modified_" + file;
            // Ensure saving the file with third-party quirks doesn't crash the libzip archiver
            REQUIRE_NOTHROW(doc.saveAs(outFile, XLForceOverwrite));
            doc.close();

            // Ensure the newly packed file remains structurally sound for OpenXLSX
            XLDocument doc2;
            REQUIRE_NOTHROW(doc2.open(outFile));
            auto wks2 = doc2.workbook().worksheet(sheetNames[0]);
            REQUIRE(wks2.cell("ZZ99").value().get<std::string>() == "OpenXLSX Compatibility Mark");
            doc2.close();

            std::filesystem::remove(outFile);
        }
    }
}