#include <catch2/catch_test_macros.hpp>
#include "OpenXLSX.hpp"
#include <iostream>
#include <fstream>

using namespace OpenXLSX;

TEST_CASE("Macro Preservation (.xlsm)", "[XLMacro]")
{
    // Generate a dummy xlsm with a fake bin file
    {
        XLDocument doc1;
        doc1.create("./DummyMacro.xlsm", XLForceOverwrite);
        auto wks = doc1.workbook().worksheet("Sheet1");
        wks.cell("A1").value() = "Has Macro";
        
        // Inject a fake vbaProject.bin into the archive via streamed file
        // We can create a tiny binary file
        std::ofstream binFile("dummy_vba.bin", std::ios::binary);
        binFile << "FAKE_MACRO_PAYLOAD_12345";
        binFile.close();

        doc1.addStreamedFile("xl/vbaProject.bin", "dummy_vba.bin");
        
        // Need to add relationship to workbook
        doc1.workbookRelationships().addRelationship(XLRelationshipType::VBAProject, "vbaProject.bin");
        doc1.save();
    }

    // Now reload it and save again, verify it survives
    {
        XLDocument doc2;
        doc2.open("./DummyMacro.xlsm");
        REQUIRE(doc2.hasMacro() == true);
        
        auto wks = doc2.workbook().worksheet("Sheet1");
        wks.cell("B1").value() = "Modified Data";
        
        doc2.saveAs("./DummyMacro_Resaved.xlsm", XLForceOverwrite);
    }

    // Load the 3rd time to check if it's there
    {
        XLDocument doc3;
        doc3.open("./DummyMacro_Resaved.xlsm");
        REQUIRE(doc3.hasMacro() == true);
        
        // Extract it to memory to verify the payload is identical
        std::string payload = doc3.archive().getEntry("xl/vbaProject.bin");
        REQUIRE(payload == "FAKE_MACRO_PAYLOAD_12345");
        
        // Check content types
        std::string ctStr = doc3.archive().getEntry("[Content_Types].xml");
        REQUIRE(ctStr.find("vbaProject") != std::string::npos);
        // The root workbook override should be macroEnabled
        REQUIRE(ctStr.find("application/vnd.ms-excel.sheet.macroEnabled.main+xml") != std::string::npos);
    }

    std::remove("dummy_vba.bin");
}


TEST_CASE("Macro Preservation (.xlsm) using external file", "[XLMacro]")
{
    // Try to open a file generated by a real external tool (excelize)
    {
        XLDocument doc1;
        doc1.open("./Tests/excelize_macro.xlsm");
        REQUIRE(doc1.hasMacro() == true);
        
        auto wks = doc1.workbook().worksheet("Sheet1");
        wks.cell("A2").value() = "Modified by OpenXLSX";
        
        doc1.saveAs("./Tests/excelize_macro_resaved.xlsm", XLForceOverwrite);
    }

    {
        XLDocument doc2;
        doc2.open("./Tests/excelize_macro_resaved.xlsm");
        REQUIRE(doc2.hasMacro() == true);
        
        std::string payload = doc2.archive().getEntry("xl/vbaProject.bin");
        REQUIRE(payload.size() > 1000); // A real vbaProject.bin is usually several KB

        std::string ctStr = doc2.archive().getEntry("[Content_Types].xml");
        REQUIRE(ctStr.find("application/vnd.ms-excel.sheet.macroEnabled.main+xml") != std::string::npos);
        REQUIRE(ctStr.find("application/vnd.ms-office.vbaProject") != std::string::npos);
    }

        {
        XLDocument doc_verify_source;
        doc_verify_source.open("./Tests/excelize_macro.xlsm");
        auto wks_src = doc_verify_source.workbook().worksheet("Sheet1");
        // Ensure A2 is empty in the original file, meaning saveAs did NOT corrupt the source!
        REQUIRE(wks_src.cell("A2").value().type() == XLValueType::Empty);
    }

    std::remove("./Tests/excelize_macro_resaved.xlsm");
    }
