#include "OpenXLSX.hpp"
#include <catch2/catch_test_macros.hpp>
#include <fstream>
#include <iostream>

using namespace OpenXLSX;

namespace { 
inline const std::string& __global_unique_file_0() {
    static std::string name = OpenXLSX::TestHelpers::getUniqueFilename("__SanitizedFile_xlsx") + ".xlsx";
    return name;
}

inline const std::string& __global_unique_file_1() {
    static std::string name = OpenXLSX::TestHelpers::getUniqueFilename("__DummyMacro_xlsm") + ".xlsm";
    return name;
}

inline const std::string& __global_unique_file_2() {
    static std::string name = OpenXLSX::TestHelpers::getUniqueFilename("__DummyMacro_Resaved_xlsm") + ".xlsm";
    return name;
}

inline const std::string& __global_unique_file_3() {
    static std::string name = OpenXLSX::TestHelpers::getUniqueFilename("__MacroMutationSource_xlsm") + ".xlsm";
    return name;
}
} // namespace


TEST_CASE("MacroPreservationxlsm", "[XLMacro]")
{
    // Generate a dummy xlsm with a fake bin file
    {
        XLDocument doc1;
        doc1.create(__global_unique_file_1(), XLForceOverwrite);
        auto wks               = doc1.workbook().worksheet("Sheet1");
        wks.cell("A1").value() = "Has Macro";

        // Inject a fake vbaProject.bin into the archive via streamed file
        // We can create a tiny binary file
        std::ofstream binFile("dummy_vba.bin", std::ios::binary);
        binFile << "FAKE_MACRO_PAYLOAD_12345";
        binFile.close();

        doc1.addStreamedFile("xl/vbaProject.bin", "dummy_vba.bin");

        // Need to add relationship to workbook
        doc1.workbookRelationships().addRelationship(XLRelationshipType::VBAProject, "vbaProject.bin");
        doc1.save();
    }

    // Now reload it and save again, verify it survives
    {
        XLDocument doc2;
        doc2.open(__global_unique_file_1());
        REQUIRE(doc2.hasMacro() == true);

        auto wks               = doc2.workbook().worksheet("Sheet1");
        wks.cell("B1").value() = "Modified Data";

        doc2.saveAs(__global_unique_file_2(), XLForceOverwrite);
    }

    // Load the 3rd time to check if it's there
    {
        XLDocument doc3;
        doc3.open(__global_unique_file_2());
        REQUIRE(doc3.hasMacro() == true);

        // Extract it to memory to verify the payload is identical
        std::string payload = doc3.extractXmlFromArchive("xl/vbaProject.bin");
        REQUIRE(payload == "FAKE_MACRO_PAYLOAD_12345");

        // Check content types
        std::string ctStr = doc3.extractXmlFromArchive("[Content_Types].xml");
        REQUIRE(ctStr.find("vbaProject") != std::string::npos);
        // The root workbook override should be macroEnabled
    }

    // Cleanup generated files
    std::remove("dummy_vba.bin");
    std::remove(__global_unique_file_1());
    std::remove(__global_unique_file_2());
}

TEST_CASE("MacroExtensionMutationandSanitization", "[XLMacro][Security]")
{
    // Test that when a .xlsm is loaded but saved as .xlsx, the macro is intentionally stripped
    // to prevent Excel from complaining about file extension mismatch and potential security risks.
    {
        XLDocument doc;
        doc.create(__global_unique_file_3(), XLForceOverwrite);

        std::ofstream binFile("dummy_vba2.bin", std::ios::binary);
        binFile << "VIRUS_PAYLOAD";
        binFile.close();

        doc.addStreamedFile("xl/vbaProject.bin", "dummy_vba2.bin");
        doc.workbookRelationships().addRelationship(XLRelationshipType::VBAProject, "vbaProject.bin");
        doc.save();
    }

    {
        XLDocument doc;
        doc.open(__global_unique_file_3());
        REQUIRE(doc.hasMacro() == true);

        // Explicitly sanitize the document before saving as standard xlsx
        doc.deleteMacro();
        REQUIRE(doc.hasMacro() == false);

        doc.saveAs(__global_unique_file_0(), XLForceOverwrite);
    }

    {
        // Load the sanitized file to prove the payload is completely gone
        XLDocument doc;
        doc.open(__global_unique_file_0());
        REQUIRE(doc.hasMacro() == false);

        bool hasVbaProject = false;
        for (const auto& entry : doc.archive().entryNames()) {
            if (entry.find("vbaProject") != std::string::npos) { hasVbaProject = true; }
        }
        REQUIRE_FALSE(hasVbaProject);    // Binary file must be annihilated

        // Verify relationships are clean
        auto rels = doc.workbookRelationships().relationships();
        for (const auto& rel : rels) { REQUIRE(rel.type() != XLRelationshipType::VBAProject); }

        // Verify ContentTypes are clean
        std::string ctStr = doc.archive().getEntry("[Content_Types].xml");
        REQUIRE(ctStr.find("vbaProject") == std::string::npos);
    }

    // Cleanup generated files
    std::remove("dummy_vba2.bin");
    std::remove(__global_unique_file_3());
    std::remove(__global_unique_file_0());
}

TEST_CASE("MacroPreservationxlsmusingexternalfile", "[XLMacro]")
{
    // Try to open a file generated by a real external tool (excelize)
    {
        XLDocument doc1;
        doc1.open("./Tests/excelize_macro.xlsm");
        REQUIRE(doc1.hasMacro() == true);

        auto wks               = doc1.workbook().worksheet("Sheet1");
        wks.cell("A2").value() = "Modified by OpenXLSX";

        doc1.saveAs("./Tests/excelize_macro_resaved.xlsm", XLForceOverwrite);
    }

    {
        XLDocument doc2;
        doc2.open("./Tests/excelize_macro_resaved.xlsm");
        REQUIRE(doc2.hasMacro() == true);

        std::string payload = doc2.extractXmlFromArchive("xl/vbaProject.bin");
        REQUIRE(payload.size() > 1000);    // A real vbaProject.bin is usually several KB

        std::string ctStr = doc2.extractXmlFromArchive("[Content_Types].xml");
        REQUIRE(ctStr.find("application/vnd.ms-excel.sheet.macroEnabled.main+xml") != std::string::npos);
        REQUIRE(ctStr.find("application/vnd.ms-office.vbaProject") != std::string::npos);
    }

    {
        XLDocument doc_verify_source;
        doc_verify_source.open("./Tests/excelize_macro.xlsm");
        auto wks_src = doc_verify_source.workbook().worksheet("Sheet1");
        // Ensure A2 is empty in the original file, meaning saveAs did NOT corrupt the source!
        REQUIRE(wks_src.cell("A2").value().type() == XLValueType::Empty);
    }

    std::remove("./Tests/excelize_macro_resaved.xlsm");
}
