#include <OpenXLSX.hpp>
#include <catch2/catch_all.hpp>
#include "TestHelpers.hpp"
#include <filesystem>
#include <iostream>
#include <string>
#include <vector>

using namespace OpenXLSX;

namespace { 
inline const std::string& __global_unique_file_0() {
    static std::string name = OpenXLSX::TestHelpers::getUniqueFilename("excelize_generated_xlsx") + ".xlsx";
    return name;
}
} // namespace


TEST_CASE("CrossEngineCompatibility", "[Compatibility]")
{
    // These files are generated by scripts and have known structures
    std::vector<std::string> generatorFiles = {"openpyxl_generated.xlsx", __global_unique_file_0()};

    // These files are static exports from various SaaS/Desktop platforms
    std::vector<std::string> realWorldFiles = {"google_spreadsheets.xlsx", "tencent_sheet.xlsx"};

    auto resolvePath = [](const std::string& file) -> std::string {
        std::string filepath = "Fixtures/" + file;
        if (!std::filesystem::exists(filepath)) {
            if (std::filesystem::exists("Tests/Fixtures/" + file)) { filepath = "Tests/Fixtures/" + file; }
            else if (std::filesystem::exists(file)) { filepath = file; }
            else {
                filepath = "../Tests/Fixtures/" + file;
            }
        }
        return filepath;
    };

    for (const auto& file : generatorFiles) {
        SECTION("Load, verify and re-save generator file: " + file)
        {
            std::string filepath = resolvePath(file);
            if (!std::filesystem::exists(filepath)) FAIL("Test fixture not found: " << file);

            INFO("Testing compatibility with: " << filepath);

            XLDocument doc;
            REQUIRE_NOTHROW(doc.open(filepath));

            auto wks = doc.workbook().worksheet("TestSheet");

            // 1. Verify Basic Values
            REQUIRE(wks.cell("A1").value().get<std::string>().find("Hello from") != std::string::npos);
            REQUIRE(wks.cell("A2").value().get<int64_t>() == 42);
            REQUIRE(wks.cell("A3").value().get<double>() == Catch::Approx(3.1415));

            // Note: Date/Time might be read as a float (Excel serial date) depending on OpenXLSX parsing,
            // but we at least ensure it doesn't crash and has a value.
            REQUIRE(wks.cell("A4").value().type() != XLValueType::Empty);

            // Formulas
            REQUIRE(wks.cell("A5").hasFormula() == true);
            REQUIRE(wks.cell("A5").formula().get().find("SUM") != std::string::npos);

            // Styling presence check
            REQUIRE(wks.cell("B1").value().get<std::string>() == "Styled");

            // Merged Cells check
            REQUIRE(wks.cell("C1").value().get<std::string>() == "Merged Area");

            // Second Sheet
            auto wks2_orig = doc.workbook().worksheet("SecondSheet");
            REQUIRE(wks2_orig.cell("A1").value().get<std::string>() == "Data in second sheet");

            // 2. Modify content
            wks.cell("C1").value() = "Modified by OpenXLSX";

            // 3. Save as new file (this ensures we don't break the original but tests the write-path)
            std::string outFile = "modified_" + file;
            REQUIRE_NOTHROW(doc.saveAs(outFile, XLForceOverwrite));
            doc.close();

            // 4. Re-open to verify our write didn't corrupt it
            XLDocument doc2;
            REQUIRE_NOTHROW(doc2.open(outFile));
            auto wks2 = doc2.workbook().worksheet("TestSheet");
            REQUIRE(wks2.cell("C1").value().get<std::string>() == "Modified by OpenXLSX");
            doc2.close();

            std::filesystem::remove(outFile);
        }
    }

    for (const auto& file : realWorldFiles) {
        SECTION("Load, verify and re-save real-world file: " + file)
        {
            std::string filepath = resolvePath(file);
            if (!std::filesystem::exists(filepath)) {
                WARN("Real-world fixture missing, skipping test: " << file);
                return;    // Skip if user hasn't downloaded them
            }

            INFO("Testing compatibility with: " << filepath);

            XLDocument doc;
            // Ensure OpenXLSX can successfully parse the file
            REQUIRE_NOTHROW(doc.open(filepath));

            // Ensure we can retrieve at least one worksheet
            auto sheetNames = doc.workbook().worksheetNames();
            REQUIRE_FALSE(sheetNames.empty());

            auto wks = doc.workbook().worksheet(sheetNames[0]);

            // If this is the specific Google Spreadsheets fixture we know about, do targeted assertions
            if (file == "google_spreadsheets.xlsx") {
                INFO("Performing targeted assertions for Google Sheets layout");

                // Dates/Headers row (Row 3 and 4)
                // Google Sheets exports dates as floats (serial numbers) if they are true dates
                auto c3_val = wks.cell("C3").value().type();
                if (c3_val == XLValueType::String) { REQUIRE(wks.cell("C3").value().get<std::string>().find("9月") != std::string::npos); }
                else if (c3_val == XLValueType::Float) {
                    REQUIRE(wks.cell("C3").value().get<double>() > 40000.0);    // Simple date sanity check
                }

                auto c4_val = wks.cell("C4").value().type();
                if (c4_val == XLValueType::String) {
                    // It might be a formula or calculated rich text, so just check it exists
                    auto str = wks.cell("C4").value().get<std::string>();
                    REQUIRE(!str.empty());
                }
                else {
                    // In some cases Google Sheets uses styles or custom formats for weekdays, we just ensure it parses.
                    REQUIRE(wks.cell("C4").value().type() != XLValueType::Error);
                }

                auto i3_val = wks.cell("I3").value().type();
                if (i3_val == XLValueType::String) { REQUIRE(wks.cell("I3").value().get<std::string>().find("9月") != std::string::npos); }
                else if (i3_val == XLValueType::Float) {
                    REQUIRE(wks.cell("I3").value().get<double>() > 40000.0);
                }

                auto b5_val = wks.cell("B5").value().type();
                if (b5_val == XLValueType::String) {
                    auto str = wks.cell("B5").value().get<std::string>();
                    REQUIRE(!str.empty());
                }
                else {
                    REQUIRE(b5_val == XLValueType::Float);
                }

                // Footer areas (Row 28)
                auto b28_val = wks.cell("B28").value().type();
                if (b28_val == XLValueType::String) {
                    REQUIRE(wks.cell("B28").value().get<std::string>().find("备注") != std::string::npos);
                }
                auto g28_val = wks.cell("G28").value().type();
                if (g28_val == XLValueType::String) {
                    REQUIRE(wks.cell("G28").value().get<std::string>().find("待办事项") != std::string::npos);
                }
            }

            if (file == "tencent_sheet.xlsx") {
                INFO("Performing targeted assertions for Tencent Docs layout");

                // Titles and Headers
                auto a1_val = wks.cell("A1").value().type();
                if (a1_val == XLValueType::String) {
                    REQUIRE(wks.cell("A1").value().get<std::string>().find("欢迎使用腾讯文档在线表格") != std::string::npos);
                }

                auto a3_val = wks.cell("A3").value().type();
                if (a3_val == XLValueType::String) {
                    REQUIRE(wks.cell("A3").value().get<std::string>().find("一、信息统计") != std::string::npos);
                }

                auto a14_val = wks.cell("A14").value().type();
                if (a14_val == XLValueType::String) {
                    REQUIRE(wks.cell("A14").value().get<std::string>().find("二、工作汇报") != std::string::npos);
                }

                // First Table Headers (Row 5)
                auto a5_val = wks.cell("A5").value().type();
                if (a5_val == XLValueType::String) { REQUIRE(wks.cell("A5").value().get<std::string>().find("姓名") != std::string::npos); }
                auto c5_val = wks.cell("C5").value().type();
                if (c5_val == XLValueType::String) {
                    REQUIRE(wks.cell("C5").value().get<std::string>().find("联系电话") != std::string::npos);
                }

                // First Table Data (Row 6)
                auto a6_val = wks.cell("A6").value().type();
                if (a6_val == XLValueType::String) {
                    REQUIRE(wks.cell("A6").value().get<std::string>().find("minren") != std::string::npos);
                }

                // Phone numbers and QQ numbers might be stored as Floats/Ints or Strings
                auto c6_val = wks.cell("C6").value().type();
                if (c6_val == XLValueType::String) {
                    REQUIRE(wks.cell("C6").value().get<std::string>().find("15812345678") != std::string::npos);
                }
                else if (c6_val == XLValueType::Float) {
                    REQUIRE(wks.cell("C6").value().get<double>() == Catch::Approx(15812345678.0));
                }
                else if (c6_val == XLValueType::Integer) {
                    REQUIRE(wks.cell("C6").value().get<int64_t>() == 15812345678LL);
                }

                auto d6_val = wks.cell("D6").value().type();
                if (d6_val == XLValueType::String) {
                    REQUIRE(wks.cell("D6").value().get<std::string>().find("123456789") != std::string::npos);
                }
                else if (d6_val == XLValueType::Float) {
                    REQUIRE(wks.cell("D6").value().get<double>() == Catch::Approx(123456789.0));
                }
                else if (d6_val == XLValueType::Integer) {
                    REQUIRE(wks.cell("D6").value().get<int64_t>() == 123456789LL);
                }

                // Second Table Headers (Row 16)
                auto a16_val = wks.cell("A16").value().type();
                if (a16_val == XLValueType::String) {
                    REQUIRE(wks.cell("A16").value().get<std::string>().find("部门") != std::string::npos);
                }
                auto c16_val = wks.cell("C16").value().type();
                if (c16_val == XLValueType::String) {
                    REQUIRE(wks.cell("C16").value().get<std::string>().find("完成度") != std::string::npos);
                }

                // Second Table Data (Row 17)
                auto a17_val = wks.cell("A17").value().type();
                if (a17_val == XLValueType::String) {
                    REQUIRE(wks.cell("A17").value().get<std::string>().find("产品组") != std::string::npos);
                }

                // Percentages might be stored as Float (e.g. 1.0 for 100%) or String ("100%")
                auto c17_val = wks.cell("C17").value().type();
                if (c17_val == XLValueType::String) {
                    REQUIRE(wks.cell("C17").value().get<std::string>().find("100%") != std::string::npos);
                }
                else if (c17_val == XLValueType::Float) {
                    REQUIRE(wks.cell("C17").value().get<double>() == Catch::Approx(1.0));
                }
                else if (c17_val == XLValueType::Integer) {
                    REQUIRE(wks.cell("C17").value().get<int64_t>() == 1);
                }
            }

            // Perform a safe modification
            wks.cell("ZZ99").value() = "OpenXLSX Compatibility Mark";

            std::string outFile = "modified_" + file;
            // Ensure saving the file with third-party quirks doesn't crash the libzip archiver
            REQUIRE_NOTHROW(doc.saveAs(outFile, XLForceOverwrite));
            doc.close();

            // Ensure the newly packed file remains structurally sound for OpenXLSX
            XLDocument doc2;
            REQUIRE_NOTHROW(doc2.open(outFile));
            auto wks2 = doc2.workbook().worksheet(sheetNames[0]);
            REQUIRE(wks2.cell("ZZ99").value().get<std::string>() == "OpenXLSX Compatibility Mark");
            doc2.close();

            std::filesystem::remove(outFile);
        }
    }
}