name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cc: [clang, gcc, cl]
        cxx: [clang++, g++, cl]
        exclude:
          - os: ubuntu-latest
            cc: cl
          - os: ubuntu-latest
            cxx: cl
          - os: macos-latest
            cc: gcc
          - os: macos-latest
            cxx: g++
          - os: macos-latest
            cc: cl
          - os: macos-latest
            cxx: cl
          - os: windows-latest
            cc: clang
          - os: windows-latest
            cxx: clang++
          - os: windows-latest
            cc: gcc
          - os: windows-latest
            cxx: g++

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC (Windows only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: >
          cmake -G Ninja -B build
          -DCMAKE_BUILD_TYPE=Release
          -DOPENXLSX_BUILD_TESTS=ON
          -DOPENXLSX_BUILD_BENCHMARKS=OFF
          -DOPENXLSX_ENABLE_LTO=OFF
          -DOPENXLSX_ENABLE_UNITY_BUILD=ON
          -DOPENXLSX_OPTIMIZE_NATIVE=OFF

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest -V
